### PR TITLE
Feat/resttls/60

### LINKED ISSUE #60: [FEATURE] Rest Server TLS capability
We need to add the rest server TLS capability.

Currently the listen and serve only handles plain tcp TLS config options are present but need to add that in the server start method.

### PR DESCRIPTION
**Pull request by nandagopalan**
Added the tls server capabilities or rest.
Updated the project readme
Closes #60

### CODE REVIEW

**Review by neo7337 — APPROVED** [review]
approved

**Review by neo7337 — CHANGES_REQUESTED** [review]
test cases missing

**Comment by nandagopalan** [comment]
Moving to draft

**Review by neo7337 — APPROVED** [review]
approved

**Pull request merged**
