### PR TITLE
Feat/rest/55

### LINKED ISSUE #55: Rest Server
Turbo was intended to be low level http router, we need a rest server side capabilities reducing the boiler plate code and limiting the exposure of the routes.

### PR DESCRIPTION
**Pull request by nandagopalan**
Adde rest server capabilities using turbo.

Closes #55

### CODE REVIEW

**Review by neo7337 — DISMISSED** [review]
looks good, approved

**Review by neo7337 — DISMISSED** [review]
approved

**Comment by nandagopalan** [comment]
closes #59

**Review by neo7337 — APPROVED** [review]
approve

**Pull request merged**
